Repository kapost/codeclimate-common, pull requests merged in 2018-05, with the labels that each got.

#20 Disabled eslint consistent-return
  .eslintrc.js
Labels: affects-issue-count, js

#19 Disable ambiguous blocks in specs.
  .rubocop.kapost.yml
Labels: affects-issue-count, ruby

#18 Disable "react/prefer-stateless-function"
  .eslintrc.js
Labels: affects-issue-count, js

#17 Disabled arrow-parens to allow developer to decide
  .eslintrc.js
Labels: affects-issue-count, js

#16 Relax destructuring rules for arrays
  .eslintrc.js
Labels: affects-issue-count, js

#15 Update eslint with async-await function spacing
  .eslintrc.js
Labels: js, ok-to-merge-mid-quarter

#10 require brackets for word arrays
  .rubocop.kapost.yml
Labels: affects-issue-count, ruby

#9 require brackets for an array of symbols
  .rubocop.kapost.yml
Labels: affects-issue-count, needs-autofix, ruby
